Include python3 uuid package to fix pip3 missing dependency error
When running the script on an Banana Pi R3 with OpenWRT 23.05.2, the installation script exited with the following error:

```
Traceback (most recent call last):   File "/usr/bin/pip3", line 8, in <module>     sys.exit(main())

...


ModuleNotFoundError: No module named 'uuid'
```